### PR TITLE
Allwinner: Implement nanopi neo air

### PR DESCRIPTION
**Pull request by biotinker**
This builds off of #23 to expand support to also include the nanoPi Neo Air board. It also updates the Allwinner H3 pin mapping to properly support the PL pins, something that was missing in the #23 PR.

### CODE REVIEW

**Comment by maruel** [comment]
Ran go mod tidy and pushed. Please pull and rebase and fix CI checks.

**Comment by biotinker** [comment]
CI checks should now all be passing

**Comment by maruel** [comment]
The go mod tidy failure is abnormal since I had fixed it. Will look later what the heck is happening. Sorry about that.

**Comment by biotinker** [comment]
Extra weird is that the CI checks pass in my personal repo, but should presumably be using the exact same workflow as here...

https://github.com/biotinker/host/actions/runs/4491701924

**Comment by biotinker** [comment]
Anything I can do to help get this through? Happy to look into the failure more given a starting point

**Pull request merged**
